### ISSUE TITLE
computeProps.js issue

### ISSUE THREAD

**Issue by gititon** [GeekyAnts/native-base-boilerplate#2]
Hello, first off, thank you so much for this project. It was extremely helpful to find an example like this that has a template for the concept of a user log in and a drawer that user's see when they are logged in that invoke various stack navigators.

When I initially cloned this project a week ago and ran npm install it ran just fine, but I tried cloning it this past weekend and received the issue after running npm install, react-native link, and react-native run-android:

{"from":"/Users/me/native-base-boilerplate/node_modules/native-base/dist/src/Utils/computeProps.js","to":"react-native/Libraries/Renderer/shims/ReactNativePropRegistry","message":"Unable to resolve module `react-native/Libraries/Renderer/shims/ReactNativePropRegistry` from `/Users/me/native-base-boilerplate/node_modules/native-base/dist/src/Utils/computeProps.js`: Module does not exist in the module map or in these directories:\n  /Users/me/native-base-boilerplate/node_modules/react-native/Libraries/Renderer/shims\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}

I tried the recommended actions but that didn't help. Can you please help me determine how to clone this project and get it running again? Thank you for your help!

**Comment by agerson** [comment]
I am getting the same error.

**Comment by sankhadeeproy007** [comment]
@gititon @agerson Can you share your package.json?

**Comment by gititon** [comment]
Hi @sankhadeeproy007,

Thank you for your attention this. I can't continue development on my app until I get this working.

I clone this project, cd into the directory, run npm install, and my package.json appears as follow:

```{
  "name": "NativeBaseBoilerplate",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.2.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-navigation": "^1.0.0-beta.11"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by SupriyaKalghatgi** [comment]
@gititon I tried cloning native-base-boilerplate this morning
Here's my `package.json` and output

![screen shot 2017-07-24 at 12 59 31 pm](https://user-images.githubusercontent.com/13464885/28512544-f705a364-706f-11e7-99dd-1f7fbd3d2349.png)

**Comment by nandesu** [comment]
Any update on this? 
I'm getting the same thing. 
Oddly enough my package json appears to match SupriyaKalghatgi's exactly. hum.

{
  "name": "NativeBaseBoilerplate",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.2.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-navigation": "^1.0.0-beta.11"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.0.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by nandesu** [comment]
@gititon @agerson 
Query: Did you **npm** install? 
If you used "npm install", do the following in your native-base-boilerplate directory: 

1. rm -rf node_modules
2. yarn
3. react-native run-ios

**Comment by gititon** [comment]
Thanks a lot, @nandesu, that did the trick!

**Comment by shivrajkumar** [comment]
Yarn has been added to the cli
